### ISSUE TITLE
Message queue increased 

### ISSUE THREAD

**Issue by vitalerter** [sbtinstruments/aiomqtt#108]
Hi, 
I have a leak and according to objgraph plot it is:

```
builtin_function_or_method    70353     +5055
dict                          28189     +1011
Condition                     13649     +1011
deque                         13913     +1011
MQTTMessage                   13617     +1011
MQTTMessageInfo               13617     +1011

```

Then when i limit filtered_messages to 1500 i get also warning " Message queue is full. Discarding message."

What can be the reason?

**Comment by frederikaalund** [comment]
Hi and thanks for opening this issue. Let me have a look. :)

> Then when i limit filtered_messages to 1500 i get also warning " Message queue is full. Discarding message."

Sounds like your MQTT server sends more messages than your MQTT can handle. You have the following options:

 1. Send fewer message from the MQTT server to the MQTT client.
 2. Replace the MQTT client with a faster one.
 3. Upgrade the hardware/software of the MQTT client so that it can process messages faster

There is no silver bullet here. The best option for you depends on your use case. You have to measure/benchmark/profile to find the bottleneck. Maybe asyncio-mqtt is simply too slow for your use case or your hardware is too limited.

If you find a performance bottleneck that is specific to asyncio-mqtt, let me know. :+1:
If you benchmark asyncio-mqtt against other MQTT clients, I'd gladly link to the benchmark.

The primary goals of asyncio-mqtt is stability and maintainability. Not performance. It's python after all. :)

~Frederik

**Comment by empicano** [comment]
Hey there, I'm guessing that we can close this as there has been no more discussion. If there's anything left unclear, please reopen!
