### ISSUE TITLE
Renaming asyncio-mqtt to aiomqtt

### ISSUE THREAD

**Issue by empicano** [sbtinstruments/aiomqtt#202]
@mossblaser has kindly offered to pass the nicer aiomqtt name on to the asyncio-mqtt project, thank you again! 😎

There are some projects depending on aiomqtt, so if necessary, Jonathan wants to keep the option to publish bugfixes. That does not affect asyncio-mqtt due to the lower version number (aiomqtt is on `0.1.3`).

As for migrating to the new name, my idea would be:

1. Publish the package both under the asyncio-mqtt and the aiomqtt name
2. Change all references in the documentation to aiomqtt and log deprecation warning when asyncio-mqtt instead of aiomqtt is imported
3. Stop publishing to asyncio-mqtt on the first major release

@frederikaalund, @JonathanPlasse what do you think?

**Comment by frederikaalund** [comment]
Hey Felix, really great initiative!

I'm currently on vacation until mid next week. I'll have a more detailed look at that time.

~Frederik
________________________________
From: Felix Böhm ***@***.***>
Sent: Wednesday, March 29, 2023 2:08:44 PM
To: sbtinstruments/asyncio-mqtt ***@***.***>
Cc: Frederik Aalund ***@***.***>; Mention ***@***.***>
Subject: [sbtinstruments/asyncio-mqtt] Renaming asyncio-mqtt to aiomqtt (Issue #202)


@mossblaser<https://github.com/mossblaser> has kindly offered to pass the nicer aiomqtt name on to the asyncio-mqtt project, thank you again! 😎

There are some projects depending on aiomqtt, so if necessary, Jonathan wants to keep the option to publish bugfixes. That does not affect asyncio-mqtt due to the lower version number (aiomqtt is on 0.1.3).

As for migrating to the new name, my idea would be:

  1.  Publish the package both under the asyncio-mqtt and the aiomqtt name
  2.  Change all references in the documentation to aiomqtt and log deprecation warning when asyncio-mqtt instead of aiomqtt is imported
  3.  Stop publishing to asyncio-mqtt on the first major release

@frederikaalund<https://github.com/frederikaalund>, @JonathanPlasse<https://github.com/JonathanPlasse> what do you think?

**Comment by frederikaalund** [comment]
Alright, I'm back. :) Sorry for the delay.

Pros:

 * Reduces the number of libraries in the "async mqtt implementations in Python" space. There are plenty already so convergence is a good thing IMHO.

Cons:

 * A rename causes user inconvenience/confusion in the short run.

Personally, I think that the pros outweigh the cons. I also think that the proposed migration steps make sense. Hopefully, this minimizes user inconvenience/confusion. I vote that we aim for a *long* migration period before we disable/remove asyncio-mqtt in favor of aiomqtt. Like at least a year.

@JonathanPlasse What are your thoughts on this? :)

**Comment by vvanglro** [comment]
This is great!🥳

**Comment by JonathanPlasse** [comment]
It is good with me.

**Comment by frederikaalund** [comment]
Great! We all agree to do this. :)

@empicano do you want to take lead on this?

**Comment by empicano** [comment]
Sure, I'll do this with with the switch to poetry, I think that goes well together 😋 Could take a few days until I have time for it, though.

**Comment by frederikaalund** [comment]
Great to hear! Let me know if you need help from me at any point. :)

**Comment by skewty** [comment]
Anything holding this up?  Is there a list / milestone I can reference?  Anything we can assist with to make this happen sooner?

**Comment by empicano** [comment]
Hi there, thanks for the offer! There's some more info in the linked PR about the holdup, mainly I'm waiting on Frederik to disable the pre-commit GitHub App to be able to test the updated GitHub workflows.

**Comment by frederikaalund** [comment]
Yeah, that's on me. 😅  I just suspended the pre-commit app (see #210 for details).

**Comment by thalesmaoa** [comment]
I was using it in my requirements file and I noticed the change:

```
asyncio-mqtt @ git+https://github.com/sbtinstruments/asyncio-mqtt
```
Should be replaced to

``
aiomqtt @ git+https://github.com/sbtinstruments/aiomqtt
```

Correct?

**Comment by mossblaser** [comment]
I notice you've released a package with version 0.17.0 to PyPI. I thought the plan was to use the v1.0.0 release as a clean division between my "old" aiomqtt and this new version? Would it still be possible to do this (and to perhaps delete the v0.17.0 package to make restricting to the "old" package easier)?

Cheers!

**Comment by empicano** [comment]
Oh, doing a 1.0.0 release was not my original intention, but I see how that can be inferred from the third bullet point in my first comment, sorry for the misunderstanding! The clean division to the original aiomqtt sounds reasonable in retrospect.

I'd be nervous to rush a major version as I don't think we're ready. We _could_ roll this back and reapply it when we get there, but I don't know if that'll make things even messier. @frederikaalund what do you think?

**Comment by mossblaser** [comment]
It may not be my place to say but a change in name is pretty much a major version anyway (it is a breaking change ;)) if that helps?

**Comment by frederikaalund** [comment]
Hi everyone, sorry about the delay.

Felix and I talked the issue through over e-mail and discussed the possible mitigations. :) @empicano, thanks for pinging me here so that we can get this issue sorted out. 👍 

Long story short: I'll yank 0.17.0 from PyPI right after I write this comment. Then, I'll issue a 1.0.0 release (it's about time anyhow).

My apologies to all the user of mossblaser's aiomqtt that was inconvenienced by this renaming. I'll sort it out right away. Thanks for raising your voice!
