### ISSUE TITLE
Pin Paho to <2.0

### ISSUE THREAD

**Issue by spacemanspiff2007** [sbtinstruments/aiomqtt#278]
Paho 2.0 introduced some new mandatory arg to the [Client](https://eclipse.dev/paho/files/paho.mqtt.python/html/migrations.html#versioned-the-user-callbacks).
If this is not set a really obscure attribute error occurs:

````
Traceback (most recent call last):
  File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
AttributeError: 'Client' object has no attribute '_sock'
````

It's necessary to pin paho to < 2.0 otherwise aiomqtt will not work.

**Comment by empicano** [comment]
I thought that [paho _is_ pinned to >=1.6.0 <2.0.0](https://github.com/sbtinstruments/aiomqtt/blob/b17c310a0ee212279cbb8bfddc1d18068fe616b1/pyproject.toml#L23), or am I understanding the [poetry documentation](https://python-poetry.org/docs/dependency-specification/#caret-requirements) wrong? From the stack trace, it seems to me like the exception is thrown in paho rather than in aiomqtt.

**Comment by spacemanspiff2007** [comment]
I am still using 0.16.1 in (yet) another application which pins ``"paho-mqtt>=1.6.0"`` and I'm not a poetry user,
so I thought ```paho-mqtt = "^1.6.0"``` means the same.
I just double checked and aiomqtt 2.0.0 does indeed correcly install paho 1.6.1.
Sorry - my mistake.
