### ISSUE TITLE
Issues with uvicorn on Windows 10

### ISSUE THREAD

**Issue by realchandan** [sbtinstruments/aiomqtt#290]
I've written a very simple, reproducible script that demonstrates the error I'm facing. If I name the file `main.py`, I can run the file using `python main.py` on Windows 10, and no error is thrown. However, if I try running it with `uvicorn main:app`, it doesn't work.

I'm not sure whether this repository is the right place, or if the uvicorn repo is where I should raise this issue. Can anyone give me any hints on how to get it to work with `uvicorn main:app`?

```py
import os
import sys

if sys.platform.lower() == "win32" or os.name.lower() == "nt":
    from asyncio import WindowsSelectorEventLoopPolicy, set_event_loop_policy

    set_event_loop_policy(WindowsSelectorEventLoopPolicy())

from aiomqtt import Client
from fastapi import FastAPI

app = FastAPI()


@app.on_event("startup")
async def startup_event():
    async with Client("test.mosquitto.org") as client:
        await client.subscribe("humidity/#")
        async for message in client.messages:
            print(message.payload)


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app=app)
```

**Comment by empicano** [comment]
Hi there! Did you already find the section of [how to run aiomqtt alongside FastAPI](https://sbtinstruments.github.io/aiomqtt/alongside-fastapi-and-co.html) in our docs? 🙂

In your example, the code loops infinitely through the `async for message in client.messages:` part, which means that FastAPI can't start because the startup never finishes.

**Comment by empicano** [comment]
I'll close this then 🙂
